/*
 * This file is generated by jOOQ.
 */
package edu.java.domain.jooq.tables;


import edu.java.domain.jooq.DefaultSchema;
import edu.java.domain.jooq.Keys;
import edu.java.domain.jooq.tables.records.GithubRepositoryRecord;

import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.List;
import java.util.function.Function;

import javax.annotation.processing.Generated;

import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function5;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row5;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class GithubRepository extends TableImpl<GithubRepositoryRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>GITHUB_REPOSITORY</code>
     */
    public static final GithubRepository GITHUB_REPOSITORY = new GithubRepository();

    /**
     * The class holding records for this type
     */
    @Override
    @NotNull
    public Class<GithubRepositoryRecord> getRecordType() {
        return GithubRepositoryRecord.class;
    }

    /**
     * The column <code>GITHUB_REPOSITORY.REPOSITORY_ID</code>.
     */
    public final TableField<GithubRepositoryRecord, Long> REPOSITORY_ID = createField(DSL.name("REPOSITORY_ID"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>GITHUB_REPOSITORY.LINK_ID</code>.
     */
    public final TableField<GithubRepositoryRecord, Long> LINK_ID = createField(DSL.name("LINK_ID"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>GITHUB_REPOSITORY.FULL_NAME</code>.
     */
    public final TableField<GithubRepositoryRecord, String> FULL_NAME = createField(DSL.name("FULL_NAME"), SQLDataType.VARCHAR(1000000000).nullable(false), this, "");

    /**
     * The column <code>GITHUB_REPOSITORY.FORKS_COUNT</code>.
     */
    public final TableField<GithubRepositoryRecord, Integer> FORKS_COUNT = createField(DSL.name("FORKS_COUNT"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>GITHUB_REPOSITORY.UPDATED_AT</code>.
     */
    public final TableField<GithubRepositoryRecord, OffsetDateTime> UPDATED_AT = createField(DSL.name("UPDATED_AT"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "");

    private GithubRepository(Name alias, Table<GithubRepositoryRecord> aliased) {
        this(alias, aliased, null);
    }

    private GithubRepository(Name alias, Table<GithubRepositoryRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>GITHUB_REPOSITORY</code> table reference
     */
    public GithubRepository(String alias) {
        this(DSL.name(alias), GITHUB_REPOSITORY);
    }

    /**
     * Create an aliased <code>GITHUB_REPOSITORY</code> table reference
     */
    public GithubRepository(Name alias) {
        this(alias, GITHUB_REPOSITORY);
    }

    /**
     * Create a <code>GITHUB_REPOSITORY</code> table reference
     */
    public GithubRepository() {
        this(DSL.name("GITHUB_REPOSITORY"), null);
    }

    public <O extends Record> GithubRepository(Table<O> child, ForeignKey<O, GithubRepositoryRecord> key) {
        super(child, key, GITHUB_REPOSITORY);
    }

    @Override
    @Nullable
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    @NotNull
    public List<ForeignKey<GithubRepositoryRecord, ?>> getReferences() {
        return Arrays.asList(Keys.CONSTRAINT_B);
    }

    private transient Link _link;

    /**
     * Get the implicit join path to the <code>PUBLIC.LINK</code> table.
     */
    public Link link() {
        if (_link == null)
            _link = new Link(this, Keys.CONSTRAINT_B);

        return _link;
    }

    @Override
    @NotNull
    public GithubRepository as(String alias) {
        return new GithubRepository(DSL.name(alias), this);
    }

    @Override
    @NotNull
    public GithubRepository as(Name alias) {
        return new GithubRepository(alias, this);
    }

    @Override
    @NotNull
    public GithubRepository as(Table<?> alias) {
        return new GithubRepository(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    @NotNull
    public GithubRepository rename(String name) {
        return new GithubRepository(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    @NotNull
    public GithubRepository rename(Name name) {
        return new GithubRepository(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    @NotNull
    public GithubRepository rename(Table<?> name) {
        return new GithubRepository(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row5 type methods
    // -------------------------------------------------------------------------

    @Override
    @NotNull
    public Row5<Long, Long, String, Integer, OffsetDateTime> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function5<? super Long, ? super Long, ? super String, ? super Integer, ? super OffsetDateTime, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function5<? super Long, ? super Long, ? super String, ? super Integer, ? super OffsetDateTime, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
