/*
 * This file is generated by jOOQ.
 */
package edu.java.domain.jooq.tables.pojos;


import jakarta.validation.constraints.Size;

import java.beans.ConstructorProperties;
import java.io.Serializable;
import java.time.OffsetDateTime;

import javax.annotation.processing.Generated;

import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class StackoverflowQuestion implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long id;
    private Long linkId;
    private String title;
    private Boolean isAnswered;
    private Integer score;
    private Long answerCount;
    private OffsetDateTime lastActivityDate;

    public StackoverflowQuestion() {}

    public StackoverflowQuestion(StackoverflowQuestion value) {
        this.id = value.id;
        this.linkId = value.linkId;
        this.title = value.title;
        this.isAnswered = value.isAnswered;
        this.score = value.score;
        this.answerCount = value.answerCount;
        this.lastActivityDate = value.lastActivityDate;
    }

    @ConstructorProperties({ "id", "linkId", "title", "isAnswered", "score", "answerCount", "lastActivityDate" })
    public StackoverflowQuestion(
        @NotNull Long id,
        @Nullable Long linkId,
        @NotNull String title,
        @NotNull Boolean isAnswered,
        @NotNull Integer score,
        @NotNull Long answerCount,
        @Nullable OffsetDateTime lastActivityDate
    ) {
        this.id = id;
        this.linkId = linkId;
        this.title = title;
        this.isAnswered = isAnswered;
        this.score = score;
        this.answerCount = answerCount;
        this.lastActivityDate = lastActivityDate;
    }

    /**
     * Getter for <code>STACKOVERFLOW_QUESTION.ID</code>.
     */
    @jakarta.validation.constraints.NotNull
    @NotNull
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>STACKOVERFLOW_QUESTION.ID</code>.
     */
    public void setId(@NotNull Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>STACKOVERFLOW_QUESTION.LINK_ID</code>.
     */
    @Nullable
    public Long getLinkId() {
        return this.linkId;
    }

    /**
     * Setter for <code>STACKOVERFLOW_QUESTION.LINK_ID</code>.
     */
    public void setLinkId(@Nullable Long linkId) {
        this.linkId = linkId;
    }

    /**
     * Getter for <code>STACKOVERFLOW_QUESTION.TITLE</code>.
     */
    @jakarta.validation.constraints.NotNull
    @Size(max = 1000000000)
    @NotNull
    public String getTitle() {
        return this.title;
    }

    /**
     * Setter for <code>STACKOVERFLOW_QUESTION.TITLE</code>.
     */
    public void setTitle(@NotNull String title) {
        this.title = title;
    }

    /**
     * Getter for <code>STACKOVERFLOW_QUESTION.IS_ANSWERED</code>.
     */
    @jakarta.validation.constraints.NotNull
    @NotNull
    public Boolean getIsAnswered() {
        return this.isAnswered;
    }

    /**
     * Setter for <code>STACKOVERFLOW_QUESTION.IS_ANSWERED</code>.
     */
    public void setIsAnswered(@NotNull Boolean isAnswered) {
        this.isAnswered = isAnswered;
    }

    /**
     * Getter for <code>STACKOVERFLOW_QUESTION.SCORE</code>.
     */
    @jakarta.validation.constraints.NotNull
    @NotNull
    public Integer getScore() {
        return this.score;
    }

    /**
     * Setter for <code>STACKOVERFLOW_QUESTION.SCORE</code>.
     */
    public void setScore(@NotNull Integer score) {
        this.score = score;
    }

    /**
     * Getter for <code>STACKOVERFLOW_QUESTION.ANSWER_COUNT</code>.
     */
    @jakarta.validation.constraints.NotNull
    @NotNull
    public Long getAnswerCount() {
        return this.answerCount;
    }

    /**
     * Setter for <code>STACKOVERFLOW_QUESTION.ANSWER_COUNT</code>.
     */
    public void setAnswerCount(@NotNull Long answerCount) {
        this.answerCount = answerCount;
    }

    /**
     * Getter for <code>STACKOVERFLOW_QUESTION.LAST_ACTIVITY_DATE</code>.
     */
    @Nullable
    public OffsetDateTime getLastActivityDate() {
        return this.lastActivityDate;
    }

    /**
     * Setter for <code>STACKOVERFLOW_QUESTION.LAST_ACTIVITY_DATE</code>.
     */
    public void setLastActivityDate(@Nullable OffsetDateTime lastActivityDate) {
        this.lastActivityDate = lastActivityDate;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final StackoverflowQuestion other = (StackoverflowQuestion) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.linkId == null) {
            if (other.linkId != null)
                return false;
        }
        else if (!this.linkId.equals(other.linkId))
            return false;
        if (this.title == null) {
            if (other.title != null)
                return false;
        }
        else if (!this.title.equals(other.title))
            return false;
        if (this.isAnswered == null) {
            if (other.isAnswered != null)
                return false;
        }
        else if (!this.isAnswered.equals(other.isAnswered))
            return false;
        if (this.score == null) {
            if (other.score != null)
                return false;
        }
        else if (!this.score.equals(other.score))
            return false;
        if (this.answerCount == null) {
            if (other.answerCount != null)
                return false;
        }
        else if (!this.answerCount.equals(other.answerCount))
            return false;
        if (this.lastActivityDate == null) {
            if (other.lastActivityDate != null)
                return false;
        }
        else if (!this.lastActivityDate.equals(other.lastActivityDate))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.linkId == null) ? 0 : this.linkId.hashCode());
        result = prime * result + ((this.title == null) ? 0 : this.title.hashCode());
        result = prime * result + ((this.isAnswered == null) ? 0 : this.isAnswered.hashCode());
        result = prime * result + ((this.score == null) ? 0 : this.score.hashCode());
        result = prime * result + ((this.answerCount == null) ? 0 : this.answerCount.hashCode());
        result = prime * result + ((this.lastActivityDate == null) ? 0 : this.lastActivityDate.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("StackoverflowQuestion (");

        sb.append(id);
        sb.append(", ").append(linkId);
        sb.append(", ").append(title);
        sb.append(", ").append(isAnswered);
        sb.append(", ").append(score);
        sb.append(", ").append(answerCount);
        sb.append(", ").append(lastActivityDate);

        sb.append(")");
        return sb.toString();
    }
}
