/*
 * This file is generated by jOOQ.
 */
package edu.java.domain.jooq;


import edu.java.domain.jooq.tables.Chat;
import edu.java.domain.jooq.tables.ChatLink;
import edu.java.domain.jooq.tables.GithubRepository;
import edu.java.domain.jooq.tables.Link;
import edu.java.domain.jooq.tables.StackoverflowQuestion;

import javax.annotation.processing.Generated;


/**
 * Convenience access to all tables in the default schema.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>CHAT</code>.
     */
    public static final Chat CHAT = Chat.CHAT;

    /**
     * The table <code>CHAT_LINK</code>.
     */
    public static final ChatLink CHAT_LINK = ChatLink.CHAT_LINK;

    /**
     * The table <code>GITHUB_REPOSITORY</code>.
     */
    public static final GithubRepository GITHUB_REPOSITORY = GithubRepository.GITHUB_REPOSITORY;

    /**
     * The table <code>LINK</code>.
     */
    public static final Link LINK = Link.LINK;

    /**
     * The table <code>STACKOVERFLOW_QUESTION</code>.
     */
    public static final StackoverflowQuestion STACKOVERFLOW_QUESTION = StackoverflowQuestion.STACKOVERFLOW_QUESTION;
}
